nodebots/nodebotsday

- Readme.md
This certainly isn't a full change set.  I saw someone broadcast the wrong date already, so I thought this page should have the 2015 date up top.
> Just a quick update to put the correct date in

- Readme.md
Uruguay's Nodebots location added.
> Add Nodebots MVD location to the Readme

- Readme.md
A free nodebots day event by Makerspace Charlotte at the Discovery Place science museum with laser cutter and 3D printer support from CharMeck Library's Ideabox!
> Adding Charlotte, NC

- Readme.md
https://www.eventbrite.com.au/e/international-nodebots-day-brisbane-2015-tickets-17554488949
> Brisbane tickets

- Readme.md
Create a announcement of NodeBotsDay in Porto Alegre, south of Brasil. Maps http://bit.ly/1JdZ1Qd
> Porto alegre brasil

- Readme.md
> nodebotsday phx

- Readme.md
Added Vancouver and just alphabetised  the order of a couple of the other entries without editing them at all.
> Vancouver International Nodebotsday

- Readme.md
> add munich

- Readme.md
Inserted `<br>` after lines because markdown.
> Vancouver line formatting - doh!

- Readme.md
> update time and sponsors -PHX

- Readme.md
Fixed information about NodeBots day Singapore.
> Update Readme.md for NodeBots day Singapore

- Readme.md
Looks like this fell through the cracks (I thought it was fixed?)
> Added SF signup link

- Readme.md
Please, add info of Tokyo Event.
> Add Tokyo,Japan Event

- 2016/barcelona/README.md
Hola!
I'd like to bring the Node Bots Day to Barcelona this year.
My good friend and also bot enthusiast @alfonsofonso is joining me.
Cheers!
> Adding Barcelona venue

- 2016/events.geojson
- 2016/melbourne/README.md
> Added Melbourne, Australia

- 2016/la/README.md
> Update readme file

- 2016/seattle/readme.md
Adding the listing for the Seattle CoderDojo event for kids.
> Adding Seattle

- 2016/events.geojson
Added Seattle and fixed Melbourne, which appeared to have its lat/long flipped.
> Updating events.geojson

- 2016/sacramento/README.md
- Readme.md
> Add Sacramento

- Readme.md
> Added Australia

- 2016/tokyo/README.md
I added Tokyo information, so please merge!
> Add Tokyo info

- 2016/dallas/README.md
- 2016/events.geojson
- Readme.md
> Add Dallas Event

- 2016/events.geojson
- 2016/phoenix/README.md
- Readme.md
> Add Nodebots Day Phoenix event

- 2016/portoalegre/README.md
- Readme.md
We are confirming time, speakers and sponsors.
> Add Porto Alegre- Brazil

- 2016/chicago/README.md
- Readme.md
Adding some links & improvements
> Updating links for Chicago Nodebots day

- 2016/events.geojson
- 2016/mexico/README.md
- Readme.md
> add Mexico Event

- 2016/phoenix/README.md
thanks @ Octoblu !
@chrismatthieu
> add sponsor for PHX 

- 2017/Houston/README.md
- 2017/_template/README.md
- 2017/events.geojson
- Readme.md
Proposing July 29th, 2017 for NBD
> Blank slate for 2017

- 2017/Bogota/README.md
- 2017/events.geojson
- Readme.md
Updated on template, geojson and readme 👯
> Add Bogotá DC to the list

- 2017/Memphis/README.md
- 2017/events.geojson
- Readme.md
Tickets will go on sale later this week.
> Added Memphis TN USA

- 2017/Salvador/README.md
- 2017/events.geojson
Adding informations for the event in Bahia, Brazil.
> Added Salvador to the list

- 2018/Miami/README.md
- 2018/West_Palm_Beach/README.md
- 2018/_template/README.md
- 2018/events.geojson
- Readme.md
- SUGGESTED a day
- Creating 2018
- Adding the cities I know are already ready
- Making suggestions to changes to the front page (resetting the cities)
- Updating the GeoJSON file to include the two cities that are ready!
> Let's start 2018

- 2018/Chicago/README.md
- 2018/events.geojson
- Readme.md
> Adding Chicago event to International Nodebots Day

- 2018/Chicago/README.md
- 2018/Norfolk/README.md
- 2018/events.geojson
- Readme.md
Let's put Norfolk on the list! Thanks!
> Added Norfolk for 2018

- 2018/Phoenix/README.md
- 2018/events.geojson
- Readme.md
probably should have done this already :)
> Add Phoenix

- 2018/Melbourne/README.md
- 2018/events.geojson
Ooops - probably should have done this a month ago. NodeBots WEEKEND though in Melbourne this year - woop!
> Added Melbourne, AU

- 2019/Miami_Fort_Lauderdale/README.md
- 2019/events.geojson
- Readme.md
Adding Miami & Fort Lauderdale Locations
You guys beat me to it! But can't wait for this WONDERFUL Monthly event.
Pictures from last year:
https://www.meetup.com/BocaJS/photos/29112765/473290342/
> Adding Miami & Fort Lauderdale Locations
